cargo-features = ["edition2024"]

[package]
name = "rust"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.release]
opt-level = 3
debug = false
lto = "thin"
codegen-units = 1